CREATE TABLE [dbo].[grupoEANs](
        [GrupoEANId] [int] IDENTITY(1,1) NOT NULL,
        [Chave] [varchar](100) NOT NULL,
 CONSTRAINT [grupoEANs_pkey] PRIMARY KEY CLUSTERED 
(
        [GrupoEANId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
